import { executeQuery } from "@/lib/oracle";

export async function GET(req) {
  try {
    const query = `
SELECT 
    'IDE' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%STAGE-IDE%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%STAGE-IDE%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'DEDUPE' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%DEDUPE%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%DEDUPE%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'GET RESULT IDEB' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%GET RESULT IDEB%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%GET RESULT IDEB%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'UPLOAD DOC' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%UPLOAD DOC%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%UPLOAD DOC%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'DDE' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%DDE%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%DDE%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'VERIN' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%VERIN%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%VERIN%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'OTOR VERIN' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%OTOR VERIN%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%OTOR VERIN%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'ORDER KJPP' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%ORDER KJPP%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%ORDER KJPP%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'APPRAISAL' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%APPRAISAL%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%APPRAISAL%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'OTOR APPRAISAL' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%OTOR APPRAISAL%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%OTOR APPRAISAL%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'APPROVAL' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%APPROVAL%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%APPROVAL%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'SP3' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%SP3%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%SP3%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'ORDER NOTARIS' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%ORDER NOTARIS%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%ORDER NOTARIS%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
UNION ALL
SELECT 
    'ORDER NOTARIS FOD' AS CATEGORY,
    COUNT(CASE WHEN FLOW_CODE LIKE '%ORDER NOTARIS FOD%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND TRUNC(CREATE_DATE) = TRUNC(SYSDATE) 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "IN",
    COUNT(CASE WHEN FLOW_CODE LIKE '%ORDER NOTARIS FOD%' 
               AND FLOW_CODE NOT LIKE '%REJECT%' 
               AND JENIS_PRODUK LIKE '%GRIYA%' 
           THEN 1 END) AS "LAST"
FROM ILOS.TBL_APLIKASI
`;
    const datas = await executeQuery(query);

    return Response.json({ success: true, data: datas });
  } catch (error) {
    return Response.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
