import { executeQuery } from "@/lib/oracle";
import { NextResponse } from 'next/server';

export async function GET(req) {
    
  try {
    const kodeArea = req.nextUrl.searchParams.get("kode_area");
    const kodeRegion = req.nextUrl.searchParams.get("kode_region");

    //real
    // const tgll = new Date().toISOString().slice(0, 10);

    // dummy
    const tgll = '2024-05-02';
    
    // Dummy kode region/area (nanti bisa diganti dari DB)
    let ro_se = kodeRegion === 'All' ? 'All' : kodeRegion;
    let ar_se = kodeArea === 'All' ? 'All' : kodeArea;
    
    let whereArea = '';
    if (kodeRegion && kodeRegion !== 'All') {
    whereArea += `AND (
        CASE
        WHEN b.LVL = '2' THEN (
            SELECT c.BRANCH_CODE FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE = b.PARENT_ID
        )
        WHEN b.LVL = '3' THEN (
            SELECT c.BRANCH_CODE FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE = b.PARENT_ADMINISTRASI
        )
        ELSE ''
        END
        ) = '${ro_se}' `;
    }
    
    if (kodeArea && kodeArea !== 'All') {
    whereArea += `AND (
        CASE
        WHEN b.LVL = '2' THEN b.BRANCH_CODE
        WHEN b.LVL = '3' THEN (
            SELECT c.BRANCH_CODE FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE = b.PARENT_ID
        )
        ELSE ''
        END
        ) = '${ar_se}' `;
    }
    
    // Query utama
    // NOTE kolom tambahan region di report ff lama kenapa where nya ke area bukan ke kode ?
    const fullQuery = `
    SELECT
REGION,
KODE_AREA,
NAMA_AREA,
COUNT(*) AS TOTAL_APLIKASI,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%IDE%') THEN 1 ELSE NULL END) END) AS IDE,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%DEDUPE%') THEN 1 ELSE NULL END) END) AS DEDUPE,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%BI-CHECKING%') THEN 1 ELSE NULL END) END) AS IDEB,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%UPLOAD-DOC%') THEN 1 ELSE NULL END) END) AS UPLOAD_DOC,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%DDE%') THEN 1 ELSE NULL END) END) AS DDE,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE 'STAGE-VERIN%')) THEN 1 ELSE NULL END) END) AS VERIN,
    COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE 'STAGE-OTORISASI-VERIN%')) THEN 1 ELSE NULL END) END) AS OTOR_VERIN,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE '%VALID%')) THEN 1 ELSE NULL END) END) AS VALID,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%APPROVAL%') THEN 1 ELSE NULL END) END) AS APPROVAL,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE '%SP3%') OR (FLOW_CODE LIKE '%ORDER-AKAD%') OR (FLOW_CODE LIKE '%REVIEW-AKAD%')) THEN 1 ELSE NULL END) END) AS SP3,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE 'STAGE-AKAD-DAN-PENCAIRAN%')) THEN 1 ELSE NULL END) END) AS AKAD,
    COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE 'STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%')) THEN 1 ELSE NULL END) END) AS OTOR_AKAD,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE 'STAGE-REVIEW-DAN-PENCAIRAN%')) THEN 1 ELSE NULL END) END) AS REVIEW,
    COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN ((FLOW_CODE LIKE 'STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%')) THEN 1 ELSE NULL END) END) AS OTOR_REVIEW,
  COUNT(CASE WHEN (FLOW_CODE NOT LIKE '%REJECT%') THEN 
    (CASE WHEN (FLOW_CODE LIKE '%LIVE%') THEN 1 ELSE NULL END) END) AS LIVE,
  COUNT(CASE WHEN (FLOW_CODE LIKE '%REJECT%') THEN 
    (CASE WHEN ((SELECT COUNT(*) FROM ILOS.TBL_CANCEL_APLIKASI c WHERE c.NO_APLIKASI = a.NO_APLIKASI) > 0) THEN 1 ELSE NULL END) END) AS CANCEL,
  COUNT(CASE WHEN (FLOW_CODE LIKE '%REJECT%') THEN 
    (CASE WHEN ((SELECT COUNT(*) FROM ILOS.TBL_CANCEL_APLIKASI c WHERE c.NO_APLIKASI = a.NO_APLIKASI) <= 0) THEN 1 ELSE NULL END) END) AS REJECT,
  


  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%IDE%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_IDE,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%DEDUPE%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_DEDUPE,
  

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%BI-CHECKING%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_IDEB,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%UPLOAD-DOC%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_UPLOAD,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%DDE%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_DDE,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((a.FLOW_CODE LIKE 'STAGE-VERIN%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_VERIN,

(SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((a.FLOW_CODE LIKE 'STAGE-OTORISASI-VERIN%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_OTOR_VERIN,

(SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((a.FLOW_CODE LIKE '%VALID%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_VALID,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%APPROVAL%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_APPROVAL,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((a.FLOW_CODE LIKE '%SP3%') OR (a.FLOW_CODE LIKE '%ORDER-AKAD%') OR (a.FLOW_CODE LIKE '%REVIEW-AKAD%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_SP3,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((a.FLOW_CODE LIKE 'STAGE-AKAD-DAN-PENCAIRAN%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_AKAD,

(SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((a.FLOW_CODE LIKE 'STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_OTOR_AKAD,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((FLOW_CODE LIKE 'STAGE-REVIEW-DAN-PENCAIRAN%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_REVIEW,

(SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND ((FLOW_CODE LIKE 'STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%')) AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_OTOR_REVIEW,

  (SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (A.FLOW_CODE NOT LIKE '%REJECT%') AND (a.FLOW_CODE LIKE '%LIVE%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_LIVE,

  (SELECT
  
      COUNT(CASE WHEN (FLOW_CODE LIKE '%REJECT%') THEN 
    (CASE WHEN ((SELECT COUNT(*) FROM ILOS.TBL_CANCEL_APLIKASI c WHERE c.NO_APLIKASI = a.NO_APLIKASI) > 0) THEN 1 ELSE NULL END) END)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (a.FLOW_CODE LIKE '%REJECT%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_CANCEL,

   (SELECT
  
      COUNT(CASE WHEN (FLOW_CODE LIKE '%REJECT%') THEN 
    (CASE WHEN ((SELECT COUNT(*) FROM ILOS.TBL_CANCEL_APLIKASI c WHERE c.NO_APLIKASI = a.NO_APLIKASI) <= 0) THEN 1 ELSE NULL END) END)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE  (a.FLOW_CODE LIKE '%REJECT%') AND
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_REJECT,

(SELECT
  
      COUNT(*)
        
    FROM
      ILOS.TBL_APLIKASI a
    
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    
  WHERE 
  (a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
  (a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}) AS SUM_TOTAL

FROM 

(	SELECT
  
  CASE
    WHEN b.LVL = '2' THEN b.BRANCH_CODE
    WHEN b.LVL = '3' THEN (SELECT c.BRANCH_CODE FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE=b.PARENT_ID)
    ELSE ''
  END AS KODE_AREA,
  
  CASE
    WHEN b.LVL = '2' THEN CONCAT(CONCAT(b.BRANCH_CODE, ' - '), b.NAME)
    WHEN b.LVL = '3' THEN (SELECT CONCAT(CONCAT(c.BRANCH_CODE, ' - '), c.NAME) FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE=b.PARENT_ID)
    ELSE ''
  END AS NAMA_AREA,
  
  a.FLOW_CODE,
  rm.REGION,
  a.NO_APLIKASI
    
FROM
  ILOS.TBL_APLIKASI a

INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
LEFT JOIN ILOS.TBL_BRANCH p ON p.BRANCH_CODE = b.PARENT_ID
    LEFT JOIN REPORTFF.REGION_MAPPING RM ON RM.KODE_AREA = CASE 
        WHEN b.LVL = '2' THEN 
            b.BRANCH_CODE 
        WHEN b.LVL = '3' THEN
            p.BRANCH_CODE
        END 

WHERE 
(a.JENIS_PRODUK LIKE '%MITRAGUNA%' OR a.JENIS_PRODUK LIKE '%PENSIUN%') AND
(a.NO_APLIKASI > '20190615' AND SUBSTR(a.CREATE_DATE,1,10) < '${tgll}') 
AND (a.FLOW_CODE NOT LIKE '%_HOLD%') ${whereArea}

) A

GROUP BY REGION,KODE_AREA,NAMA_AREA

ORDER BY NAMA_AREA
    `;

    // return fullQuery;
    const datas = await executeQuery(fullQuery,[]);
    // const datas = [kodeArea,kodeRegion,tgl_awal,tgl_akhir]
    return NextResponse.json({
      success: true,
      data: datas,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
