CREATE OR REPLACE PROCEDURE ILOS.inquiry_aplikasi_split1 (
    no_apl IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
SELECT
  to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=a.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd') AS TGL_INPUT,
  a.NO_APLIKASI AS NO_APLIKASI,
  REPLACE(REPLACE(a.NAMA_CUSTOMER,'{value=',''),', storeType=java.lang.String}','') AS NAMA_NASABAH,
  REPLACE(REPLACE(a.JENIS_PRODUK,'{value=',''),', storeType=java.lang.String}','') AS JENIS_PRODUK,
  to_number(ILOS.f_get_value_clob(a.DATA,'jumlahPengajuan')) AS PLAFOND,
  CONCAT(CONCAT(b.BRANCH_CODE, ' - '), b.NAME) AS NAMA_CABANG,
CASE
    WHEN b.LVL = '2' THEN CONCAT(CONCAT(b.BRANCH_CODE, ' - '), b.NAME)
    WHEN b.LVL = '3' THEN (
        SELECT CONCAT(CONCAT(c.BRANCH_CODE, ' - '), c.NAME)
        FROM ILOS.TBL_BRANCH c
        WHERE c.BRANCH_CODE = b.PARENT_ID
    )
    ELSE ''
END AS NAMA_AREA,
  CASE
    WHEN b.LVL = '2' THEN (SELECT CONCAT(CONCAT(c.BRANCH_CODE, ' - '), c.NAME) FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE=b.PARENT_ID)
    WHEN b.LVL = '3' THEN (SELECT CONCAT(CONCAT(c.BRANCH_CODE, ' - '), c.NAME) FROM ILOS.TBL_BRANCH c WHERE c.BRANCH_CODE=b.PARENT_ADMINISTRASI)
    ELSE ''
  END AS REGION,
  CASE
    WHEN (a.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
        (SELECT CONCAT(CONCAT(c.EVENT_NO, ' - '), c.EVENT_NAME) FROM ILOS.TBL_EVENT_PENSIUN c WHERE c.EVENT_NO=ILOS.f_get_value_clob(a.DATA,'kodeProgram'))
    WHEN (a.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
        (SELECT CONCAT(CONCAT(c.EVENT_NO, ' - '), c.EVENT_NAME) FROM ILOS.TBL_EVENT_IMPLAN c WHERE c.EVENT_NO=ILOS.f_get_value_clob(a.DATA,'kodeProgram'))
    WHEN (a.JENIS_PRODUK LIKE '%GRIYA%') THEN
      (SELECT CONCAT(CONCAT(c.EVENT_NO, ' - '), c.EVENT_NAME) FROM ILOS.TBL_EVENT c WHERE c.EVENT_NO=ILOS.f_get_value_clob(a.DATA,'kodeProgram'))
  END AS EVENT,
  CASE 
    WHEN (a.FLOW_CODE LIKE '%REJECT%') THEN
      CASE
        WHEN ((SELECT COUNT(*) FROM ILOS.TBL_CANCEL_APLIKASI c WHERE c.NO_APLIKASI = a.NO_APLIKASI) > 0) THEN '88 - CANCEL'
        ELSE '99 - REJECT'
      END
    WHEN (a.FLOW_CODE NOT LIKE '%REJECT%') THEN
      CASE 
        WHEN (a.FLOW_CODE LIKE '%IDE%') THEN '10 - IDE'
        WHEN (a.FLOW_CODE LIKE '%DEDUPE%') THEN '11 - DEDUPE'
        WHEN (a.FLOW_CODE LIKE '%BI-CHECKING%') THEN '12 - iDEB'
        WHEN (a.FLOW_CODE LIKE '%UPLOAD-DOC%') THEN '13 - UPLOAD DOC'
        WHEN (a.FLOW_CODE LIKE '%DDE%') THEN '14 - DDE'
        WHEN (a.FLOW_CODE LIKE '%VERIN%') THEN '15 - VERIN'
        WHEN (a.FLOW_CODE LIKE '%OTORISASI-VERIN%') THEN '15 - VERIN'
        WHEN (a.FLOW_CODE LIKE '%APPROVAL%') THEN '16 - APPROVAL'
        WHEN (a.FLOW_CODE LIKE '%SP3%') THEN '17 - SP3'
        WHEN (a.FLOW_CODE LIKE '%ORDER-AKAD%') THEN '17 - SP3'
        WHEN (a.FLOW_CODE LIKE '%REVIEW-AKAD%') THEN '17 - SP3'
        WHEN (a.FLOW_CODE LIKE '%AKAD-DAN-PENCAIRAN%') THEN '18 - AKAD'
        WHEN (a.FLOW_CODE LIKE '%OTORISASI-AKAD-DAN-PENCAIRAN%') THEN '18 - AKAD'
        WHEN (a.FLOW_CODE LIKE '%REVIEW-DAN-PENCAIRAN%') THEN '19 - REVIEW'
        WHEN (a.FLOW_CODE LIKE '%OTORISASI-REVIEW-DAN-PENCAIRAN%') THEN '19 - REVIEW'
        WHEN (a.FLOW_CODE LIKE '%LIVE%') THEN '20 - LIVE'
        ELSE REPLACE(REPLACE(REPLACE(REPLACE(a.FLOW_CODE,'STAGE-',''),'-PENSIUN',''),'-IMPLAN',''),'-',' ')
      END
    ELSE ''
  END AS LAST_POSISI,
  a.CREATE_BY AS LAST_READ_BY,
  to_char((a.CREATE_DATE),'yyyy-mm-dd HH24:MI:SS') AS LAST_UPDATE,
  CASE
    WHEN ((SELECT count(*) FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=a.NO_APLIKASI AND h.FLOW_CODE LIKE 'STAGE-UPLOAD-DOC-%') = 0) THEN 
    (SELECT count(*) FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=a.NO_APLIKASI AND h.FLOW_CODE LIKE 'STAGE-UPLOAD-DOC-%')
    WHEN ((SELECT count(*) FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=a.NO_APLIKASI AND h.FLOW_CODE LIKE 'STAGE-UPLOAD-DOC-%') > 0) THEN 
    ((SELECT count(*) FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=a.NO_APLIKASI AND h.FLOW_CODE LIKE 'STAGE-UPLOAD-DOC-%') - 1)
  END AS JUM_RETURN
FROM
  ILOS.TBL_APLIKASI a
INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
WHERE a.NO_APLIKASI = no_apl;
END inquiry_aplikasi_split1;