import { executeQuery } from "@/lib/oracle";
import { NextResponse } from "next/server";

const getTodayJakarta = () => {
  const formatter = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Jakarta",
  });
  return formatter.format(new Date());
};

// Derived from the legacy ILOS.dashboard_daily_export procedure.
const DASHBOARD_DAILY_EXPORT_QUERY = `
WITH 
hist_ide AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY, h.CREATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-IDE%'
),
hist_dedupe AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-DEDUPE%'
),
hist_bichecking AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%'
),
hist_upload_pensiun AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY, h.CREATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE = 'STAGE-UPLOAD-DOC-PENSIUN'
),
hist_upload_implAN AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY, h.CREATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE = 'STAGE-UPLOAD-DOC-IMPLAN'
),
hist_dde AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-DDE%'
),
hist_verin AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-VERIN%'
),
hist_otorisasi_verin AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%'
),
hist_approval AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-APPROVAL%'
),
hist_sp3 AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-SP3%'
),
hist_order_akad AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%'
),
hist_review_akad AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%'
),
hist_akad AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%'
),
hist_otorisasi_akad AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%'
),
hist_review AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%'
),
hist_otorisasi_review AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE, h.UPDATE_DATE, h.UPDATE_BY,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%'
),
hist_live AS (
    SELECT h.NO_APLIKASI, h.CREATE_DATE,
           ROW_NUMBER() OVER (PARTITION BY h.NO_APLIKASI ORDER BY h.CREATE_DATE DESC) as rn
    FROM ILOS.TBL_APLIKASI_HIST h
    WHERE h.FLOW_CODE LIKE '%LIVE%'
),
upload_doc_counts AS (
    SELECT NO_APLIKASI, COUNT(*) AS cnt
    FROM ILOS.TBL_APLIKASI_HIST
    WHERE FLOW_CODE LIKE 'STAGE-UPLOAD-DOC-%'
    GROUP BY NO_APLIKASI
),
cancel_apps AS (
    SELECT NO_APLIKASI, COUNT(*) AS cnt
    FROM ILOS.TBL_CANCEL_APLIKASI
    GROUP BY NO_APLIKASI
)

SELECT
    TO_CHAR((SELECT h.CREATE_DATE FROM hist_ide h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1), 'yyyy-mm-dd') AS TGL_INPUT,
    
    app.NO_APLIKASI,
    
    REPLACE(REPLACE(REPLACE(app.NAMA_CUSTOMER,'{value=',''),', storeType=javapp.lang.String}',''),', storeType=java.lang.String}','') AS NAMA_NASABAH,
    
    REPLACE(REPLACE(REPLACE(app.JENIS_PRODUK,'{value=',''),', storeType=javapp.lang.String}',''),', storeType=java.lang.String}','') AS JENIS_PRODUK,
    
    
    TO_NUMBER(ILOS.f_get_value_clob(app.DATA, 'jumlahPengajuan')) AS PLAFOND,
    
    b.BRANCH_CODE || ' - ' || b.NAME AS NAMA_CABANG,
    
    CASE
        WHEN b.LVL = '2' THEN b.BRANCH_CODE || ' - ' || b.NAME
        WHEN b.LVL = '3' THEN (SELECT c.BRANCH_CODE || ' - ' || c.NAME 
                               FROM ILOS.TBL_BRANCH c 
                               WHERE c.BRANCH_CODE = b.PARENT_ID)
        ELSE ''
    END AS NAMA_AREA,
    
    CASE
        WHEN b.LVL = '2' THEN (SELECT c.BRANCH_CODE || ' - ' || c.NAME 
                               FROM ILOS.TBL_BRANCH c 
                               WHERE c.BRANCH_CODE = b.PARENT_ID)
        WHEN b.LVL = '3' THEN (SELECT c.BRANCH_CODE || ' - ' || c.NAME 
                               FROM ILOS.TBL_BRANCH c 
                               WHERE c.BRANCH_CODE = b.PARENT_ADMINISTRASI)
        ELSE ''
    END AS REGION,
    
    CASE 
        WHEN (app.FLOW_CODE LIKE '%REJECT%') THEN
            CASE
                WHEN (NVL((SELECT cnt FROM cancel_apps WHERE NO_APLIKASI = app.NO_APLIKASI), 0) > 0) 
                THEN '88 - CANCEL'
                ELSE '99 - REJECT'
            END
        WHEN (app.FLOW_CODE NOT LIKE '%REJECT%') THEN
            CASE 
                WHEN (app.FLOW_CODE LIKE '%IDE%') THEN '10 - IDE'
                WHEN (app.FLOW_CODE LIKE '%DEDUPE%') THEN '11 - DEDUPE'
                WHEN (app.FLOW_CODE LIKE '%BI-CHECKING%') THEN '12 - iDEB'
                WHEN (app.FLOW_CODE LIKE '%UPLOAD-DOC%') THEN '13 - UPLOAD DOC'
                WHEN (app.FLOW_CODE LIKE '%DDE%') THEN '14 - DDE'
                WHEN (app.FLOW_CODE LIKE '%VERIN%') THEN '15 - VERIN'
                WHEN (app.FLOW_CODE LIKE '%OTORISASI-VERIN%') THEN '15 - VERIN'
                WHEN (app.FLOW_CODE LIKE '%APPROVAL%') THEN '16 - APPROVAL'
                WHEN (app.FLOW_CODE LIKE '%SP3%') THEN '17 - SP3'
                WHEN (app.FLOW_CODE LIKE '%ORDER-AKAD%') THEN '17 - SP3'
                WHEN (app.FLOW_CODE LIKE '%REVIEW-AKAD%') THEN '17 - SP3'
                WHEN (app.FLOW_CODE LIKE '%AKAD-DAN-PENCAIRAN%') THEN '18 - AKAD'
                WHEN (app.FLOW_CODE LIKE '%OTORISASI-AKAD-DAN-PENCAIRAN%') THEN '18 - AKAD'
                WHEN (app.FLOW_CODE LIKE '%REVIEW-DAN-PENCAIRAN%') THEN '19 - REVIEW'
                WHEN (app.FLOW_CODE LIKE '%OTORISASI-REVIEW-DAN-PENCAIRAN%') THEN '19 - REVIEW'
                WHEN (app.FLOW_CODE LIKE '%LIVE%') THEN '20 - LIVE'
                ELSE REPLACE(REPLACE(REPLACE(REPLACE(app.FLOW_CODE,'STAGE-',''),'-PENSIUN',''),'-IMPLAN',''),'-',' ')
            END
        ELSE ''
    END AS LAST_POSISI,
    
    CASE
        WHEN (app.FLOW_CODE LIKE '%STAGE-IDE%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_ide h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.CREATE_BY FROM hist_ide h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-DEDUPE%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_dedupe h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_ide h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-BI-CHECKING%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_bichecking h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_dedupe h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-UPLOAD-DOC%') THEN
            CASE
                WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                    COALESCE(
                        (SELECT h.UPDATE_BY FROM hist_upload_pensiun h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_bichecking h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
                    )
                WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                    COALESCE(
                        (SELECT h.UPDATE_BY FROM hist_upload_implAN h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_bichecking h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
                    )
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-DDE%') THEN
            CASE
                WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                    COALESCE(
                        (SELECT h.UPDATE_BY FROM hist_dde h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_upload_pensiun h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
                    )
                WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                    COALESCE(
                        (SELECT h.UPDATE_BY FROM hist_dde h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_upload_implAN h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
                    )
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-VERIN%') OR (app.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_otorisasi_verin h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_verin h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_dde h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-APPROVAL%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_approval h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_otorisasi_verin h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_verin h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-SP3%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_sp3 h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_approval h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%') OR (app.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_review_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_order_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_approval h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%') OR (app.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%') THEN
            CASE
                WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                    COALESCE(
                        (SELECT h.UPDATE_BY FROM hist_otorisasi_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_sp3 h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
                    )
                WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                    COALESCE(
                        (SELECT h.UPDATE_BY FROM hist_otorisasi_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_review_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                        (SELECT h.UPDATE_BY FROM hist_order_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
                    )
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%') OR (app.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%') THEN
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_otorisasi_review h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_review h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_otorisasi_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_akad h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        WHEN (app.FLOW_CODE LIKE '%LIVE%') THEN 
            COALESCE(
                (SELECT h.UPDATE_BY FROM hist_otorisasi_review h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1),
                (SELECT h.UPDATE_BY FROM hist_review h WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
            )
        ELSE ''
    END AS LAST_READ_BY,
    
    CASE 
      WHEN (app.FLOW_CODE LIKE '%REJECT%') THEN
        CASE
          WHEN ((SELECT COUNT(*) FROM ILOS.TBL_CANCEL_APLIKASI c WHERE c.NO_APLIKASI = app.NO_APLIKASI) > 0) THEN '88 - CANCEL'
          ELSE '99 - REJECT'
        END
      WHEN (app.FLOW_CODE NOT LIKE '%REJECT%') THEN
        CASE 
          WHEN (app.FLOW_CODE LIKE '%IDE%') THEN '10 - IDE'
          WHEN (app.FLOW_CODE LIKE '%DEDUPE%') THEN '11 - DEDUPE'
          WHEN (app.FLOW_CODE LIKE '%BI-CHECKING%') THEN '12 - iDEB'
          WHEN (app.FLOW_CODE LIKE '%UPLOAD-DOC%') THEN '13 - UPLOAD DOC'
          WHEN (app.FLOW_CODE LIKE '%DDE%') THEN '14 - DDE'
          WHEN (app.FLOW_CODE LIKE '%VERIN%') THEN '15 - VERIN'
          WHEN (app.FLOW_CODE LIKE '%OTORISASI-VERIN%') THEN '15 - VERIN'
          WHEN (app.FLOW_CODE LIKE '%APPROVAL%') THEN '16 - APPROVAL'
          WHEN (app.FLOW_CODE LIKE '%SP3%') THEN '17 - SP3'
          WHEN (app.FLOW_CODE LIKE '%ORDER-AKAD%') THEN '17 - SP3'
          WHEN (app.FLOW_CODE LIKE '%REVIEW-AKAD%') THEN '17 - SP3'
          WHEN (app.FLOW_CODE LIKE '%AKAD-DAN-PENCAIRAN%') THEN '18 - AKAD'
          WHEN (app.FLOW_CODE LIKE '%OTORISASI-AKAD-DAN-PENCAIRAN%') THEN '18 - AKAD'
          WHEN (app.FLOW_CODE LIKE '%REVIEW-DAN-PENCAIRAN%') THEN '19 - REVIEW'
          WHEN (app.FLOW_CODE LIKE '%OTORISASI-REVIEW-DAN-PENCAIRAN%') THEN '19 - REVIEW'
          WHEN (app.FLOW_CODE LIKE '%LIVE%') THEN '20 - LIVE'
          ELSE REPLACE(REPLACE(REPLACE(REPLACE(app.FLOW_CODE,'STAGE-',''),'-PENSIUN',''),'-IMPLAN',''),'-',' ')
        END
      ELSE ''
    END AS FLOW_CODE_HIST,

    CASE
        WHEN (app.FLOW_CODE LIKE '%STAGE-IDE%') THEN
            CASE 
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (SELECT h.CREATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE 
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-DEDUPE%') THEN
            CASE 
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DEDUPE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DEDUPE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-BI-CHECKING%') THEN
            CASE 
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DEDUPE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-UPLOAD-DOC%') THEN
            CASE
              WHEN 
                (CASE
                    WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                    WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                END ) IS NULL THEN 
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE
                (CASE
                    WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                    WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                END )
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-DDE%') THEN
            CASE
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (CASE
                    WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                    WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                END )
              ELSE
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-VERIN%') OR (app.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%') THEN
            CASE  
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE  
              CASE
                  WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                  ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) 
                END
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-APPROVAL%') THEN
          CASE
            WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
              CASE
                WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) 
              END
            ELSE
              (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
          END
        WHEN (app.FLOW_CODE LIKE '%STAGE-SP3%') THEN
            CASE
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-SP3%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-SP3%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%') OR (app.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%') THEN
          CASE 
            WHEN  (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
              (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            ELSE
                CASE
                  WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                  ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                END
          END
        WHEN (app.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%') OR (app.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%') THEN
            CASE
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                  CASE	
                    WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
                      (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-SP3%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                    WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
                      CASE
                        WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%') IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                        ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                      END
                  END
              ELSE
                CASE
                  WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                  ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)  
                END
            END
        WHEN (app.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%') OR (app.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%') THEN
            CASE
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                CASE
                  WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                  ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)  
                END
              ELSE
                CASE
                  WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                  ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
                END
            END
          WHEN (app.FLOW_CODE LIKE '%LIVE%') THEN 
            CASE
              WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
              ELSE
                (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            END
        ELSE ''
      
      END AS LAST_READ_HIST,
    
    TO_CHAR(app.CREATE_DATE, 'yyyy-mm-dd HH24:MI:SS') AS LAST_UPDATE,

    CASE
        WHEN NVL((SELECT cnt FROM upload_doc_counts WHERE NO_APLIKASI = app.NO_APLIKASI), 0) = 0 THEN 0
        ELSE (SELECT cnt-1 FROM upload_doc_counts WHERE NO_APLIKASI = app.NO_APLIKASI)
    END AS JUM_RETURN,

    
    (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h 
    WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS PIC_IDE,
    TO_CHAR((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_IDE,
    TO_CHAR((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-IDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_IDE,
    
    (SELECT 
        EXTRACT(DAY FROM (ide.UPDATE_DATE - ide.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (ide.UPDATE_DATE - ide.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (ide.UPDATE_DATE - ide.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (ide.UPDATE_DATE - ide.CREATE_DATE)) || ' detik'
     FROM hist_ide ide
     WHERE  ide.NO_APLIKASI = app.NO_APLIKASI AND ide.rn = 1) AS SLA_IDE,

    (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DEDUPE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS PIC_DEDUPE,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DEDUPE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_DEDUPE,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DEDUPE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_DEDUPE,
    
    (SELECT 
        EXTRACT(DAY FROM (ddp.UPDATE_DATE - ddp.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (ddp.UPDATE_DATE - ddp.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (ddp.UPDATE_DATE - ddp.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (ddp.UPDATE_DATE - ddp.CREATE_DATE)) || ' detik'
     FROM hist_dedupe ddp
     WHERE  ddp.NO_APLIKASI = app.NO_APLIKASI AND ddp.rn = 1) AS SLA_DEDUPE,

    (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS PIC_IDEB,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_IDEB,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-BI-CHECKING%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_IDEB,
    
    (SELECT 
        EXTRACT(DAY FROM (ideb.UPDATE_DATE - ideb.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (ideb.UPDATE_DATE - ideb.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (ideb.UPDATE_DATE - ideb.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (ideb.UPDATE_DATE - ideb.CREATE_DATE)) || ' detik'
     FROM hist_bichecking ideb
     WHERE  ideb.NO_APLIKASI = app.NO_APLIKASI AND ideb.rn = 1) AS SLA_IDEB,

     CASE
        WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
          CASE 
            WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)IS NULL THEN
                (SELECT h.CREATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            ELSE 
              (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
          END
        WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
          CASE
            WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN 
              (SELECT h.CREATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            ELSE 
              (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
          END
    END AS PIC_UPLOAD,
    
    CASE
        WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
          to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
        WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
          to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
    END AS IN_UPLOAD,
    
    CASE
        WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
          to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-PENSIUN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
        WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
          to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE ='STAGE-UPLOAD-DOC-IMPLAN' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
    END AS OUT_UPLOAD,


    CASE
        WHEN app.JENIS_PRODUK LIKE '%PENSIUN%' THEN 
            (SELECT 
                EXTRACT(DAY FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' hari ' ||
                EXTRACT(HOUR FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' jam ' ||
                EXTRACT(MINUTE FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' menit ' ||
                EXTRACT(SECOND FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' detik'
             FROM hist_upload_pensiun h 
             WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
        WHEN app.JENIS_PRODUK LIKE '%MITRAGUNA%' THEN
            (SELECT 
                EXTRACT(DAY FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' hari ' ||
                EXTRACT(HOUR FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' jam ' ||
                EXTRACT(MINUTE FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' menit ' ||
                EXTRACT(SECOND FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' detik'
             FROM hist_upload_implAN h 
             WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
    END AS SLA_UPLOAD,

    (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS PIC_DDE,
    (SELECT us.BRANCH_CODE FROM ILOS.TBL_APLIKASI_HIST h INNER JOIN ILOS.TBL_USER us ON us.USER_ID = h.UPDATE_BY WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS BRANCH_DDE,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_DDE,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-DDE%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_DDE,
    
    (SELECT 
        EXTRACT(DAY FROM (dde.UPDATE_DATE - dde.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (dde.UPDATE_DATE - dde.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (dde.UPDATE_DATE - dde.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (dde.UPDATE_DATE - dde.CREATE_DATE)) || ' detik'
     FROM hist_dde dde
     WHERE  dde.NO_APLIKASI = app.NO_APLIKASI AND dde.rn = 1) AS SLA_DDE,

     CASE
      WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
      ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) 
    END AS PIC_VERIN,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_VERIN,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-VERIN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_VERIN,
    
    (SELECT 
        EXTRACT(DAY FROM (verin.UPDATE_DATE - verin.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (verin.UPDATE_DATE - verin.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (verin.UPDATE_DATE - verin.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (verin.UPDATE_DATE - verin.CREATE_DATE)) || ' detik'
     FROM hist_verin verin
     WHERE  verin.NO_APLIKASI = app.NO_APLIKASI AND verin.rn = 1) AS SLA_VERIN,

    (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS PIC_APPROVAL,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_APPROVAL,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-APPROVAL%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_APPROVAL,
    
    (SELECT 
        EXTRACT(DAY FROM (appr.UPDATE_DATE - appr.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (appr.UPDATE_DATE - appr.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (appr.UPDATE_DATE - appr.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (appr.UPDATE_DATE - appr.CREATE_DATE)) || ' detik'
     FROM hist_approval appr
     WHERE  appr.NO_APLIKASI = app.NO_APLIKASI AND appr.rn = 1) AS SLA_APPROVAL,

     CASE	
        WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
          (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-SP3%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
        WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
          CASE
            WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
            ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
          END
      END AS PIC_SP3,
      
      CASE	
        WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
          to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-SP3%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
        WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
          to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-ORDER-AKAD%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
      END AS IN_SP3,
      
      
      CASE	
        WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN 
          to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-SP3%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS')
        WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
          to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-AKAD% ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY'),'yyyy-mm-dd HH24:MI:SS')
      END AS OUT_SP3,

      CASE
    WHEN (app.JENIS_PRODUK LIKE '%PENSIUN%') THEN
        (SELECT
            EXTRACT(DAY FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' hari ' ||
            EXTRACT(HOUR FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' jam ' ||
            EXTRACT(MINUTE FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' menit ' ||
            EXTRACT(SECOND FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' detik'
         FROM hist_sp3 h
         WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
    WHEN (app.JENIS_PRODUK LIKE '%MITRAGUNA%') THEN
        (SELECT
            EXTRACT(DAY FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' hari ' ||
            EXTRACT(HOUR FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' jam ' ||
            EXTRACT(MINUTE FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' menit ' ||
            EXTRACT(SECOND FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' detik'
         FROM hist_review_akad h
         WHERE h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1)
    END AS SLA_SP3,

    CASE
      WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
      ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)  
    END AS PIC_AKAD,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_AKAD,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-AKAD-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_AKAD,
    
    (SELECT 
        EXTRACT(DAY FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' detik'
     FROM hist_otorisasi_akad h
     WHERE  h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1) AS SLA_AKAD,

     CASE
      WHEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY) IS NULL THEN (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
      ELSE (SELECT h.UPDATE_BY FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY)
    END AS PIC_REVIEW,
    to_char((SELECT h.CREATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS IN_REVIEW,
    to_char((SELECT h.UPDATE_DATE FROM ILOS.TBL_APLIKASI_HIST h WHERE h.NO_APLIKASI=app.NO_APLIKASI AND h.FLOW_CODE LIKE '%STAGE-OTORISASI-REVIEW-DAN-PENCAIRAN%' ORDER BY h.CREATE_DATE DESC FETCH FIRST 1 ROWS ONLY),'yyyy-mm-dd HH24:MI:SS') AS OUT_REVIEW,
    
    (SELECT 
        EXTRACT(DAY FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (h.UPDATE_DATE - h.CREATE_DATE)) || ' detik'
     FROM hist_otorisasi_review h
     WHERE  h.NO_APLIKASI = app.NO_APLIKASI AND h.rn = 1) AS SLA_REVIEW,

    (SELECT 
        EXTRACT(DAY FROM (live.CREATE_DATE - ide.CREATE_DATE)) || ' hari ' ||
        EXTRACT(HOUR FROM (live.CREATE_DATE - ide.CREATE_DATE)) || ' jam ' ||
        EXTRACT(MINUTE FROM (live.CREATE_DATE - ide.CREATE_DATE)) || ' menit ' ||
        EXTRACT(SECOND FROM (live.CREATE_DATE - ide.CREATE_DATE)) || ' detik'
     FROM hist_live live, hist_ide ide
     WHERE live.NO_APLIKASI = app.NO_APLIKASI AND live.rn = 1
       AND ide.NO_APLIKASI = app.NO_APLIKASI AND ide.rn = 1) AS TOTAL_SLA_LIVE

FROM
    ILOS.TBL_APLIKASI app
    INNER JOIN ILOS.TBL_BRANCH b ON b.BRANCH_CODE = app.BRANCH_CODE
WHERE 
    EXISTS (SELECT 1 FROM ILOS.TBL_APLIKASI_HIST a 
            WHERE a.NO_APLIKASI = app.NO_APLIKASI 
              AND a.UPDATE_BY IS NOT NULL 
              AND TO_CHAR(a.UPDATE_DATE, 'YYYY-MM-DD') = :p_tgl)
    AND (app.JENIS_PRODUK LIKE '%MITRAGUNA%' OR app.JENIS_PRODUK LIKE '%PENSIUN%')
    AND (
        (app.NO_APLIKASI > '20190615' AND app.BRANCH_CODE IN('10002','10033','10071','10108','10110','10144','10169','10170','10171','10275','10276','10311','10379','10429','10520','10571','10603',
            '10004','10003','10006','10067','10068','10076','10080','10229','10332','10343','10432','10463','10551','10635',
            '10005','10072','10073','10074','10075','10078','10177','10260','10261','10262','10372','10422','10430','10434','10630','10658',
            '10007','10061','10081','10082','10085','10086','10174','10263','10264','10265','10433','10509','10515','10516',
            '10017','10046','10127','10128','10129','10130','10131','10132','10198','10199','10200','10201','10288','10329','10330','10386','10420','10552',
            '10018','10020','10077','10079','10134','10135','10136','10142','10143','10230','10289','10292','10347','10376','10401','10522','10583','10629','10657',
            '10045','10069','10133','10195','10196','10197','10232','10363','10392','10435','10517','10523','10656','10660','10669',
            '10058','10035','10021','10109','10145','10146','10173','10175','10176','10212','10231','10233','10314','10553','10671',
            '10040','10012','10187','10112','10367','10378','10188','10246','10321','10322','10323','10582','10584','10451','10600','10614','10113','10280','10578','10558','10349','10460','10189','10373','10324'))
        OR (app.NO_APLIKASI > '20190703' AND app.BRANCH_CODE IN('10029','10057','10211','10163','10164','10243','10244','10245','10248','10305','10348','10478','10577','10594','10597','10598'))
        OR (app.NO_APLIKASI > '20190704' AND app.BRANCH_CODE IN('10013','10114','10115','10116','10234','10235','10236','10237','10238','10281','10406','10453'))
        OR (app.NO_APLIKASI > '20190710' AND app.BRANCH_CODE IN('10028','10048','10203','10374','10162','10255','10302','10304','10512','10659','10703','10256','10331','10350','10467','10590','10591','10202','10529','10160','10161',
            '10038','10052','10062','10064','10184','10185','10257','10317','10318','10398','10444','10464','10511','10536','10596','10601','10705'))
        OR (app.NO_APLIKASI > '20190712' AND app.BRANCH_CODE IN('10051','10060','10303','10337','10338','10339','10351','10654'))
        OR (app.NO_APLIKASI > '20190717' AND app.BRANCH_CODE IN('10054','10258','10344','10395'))
        OR (app.NO_APLIKASI > '20190718' AND app.BRANCH_CODE IN('10010','10098','10101','10104','10307','10646','10105','10273','10251','10102','10670','10497','10250','10492','10455','10719',
            '10106','10014','10099','10100','10454','10528','10117','10282','10283','10319','10103','10498'))
        OR (app.NO_APLIKASI > '20190722' AND app.BRANCH_CODE IN('10053','10031','10259','10208','10340','10499','10397','10165','10166','10308','10309'))
        OR (app.NO_APLIKASI > '20190724' AND app.BRANCH_CODE IN('10016','10066','10123','10368','10377','10462','10124','10125','10253','10254','10479','10636','10286','10287','10126','10532',
            '10015','10065','10354','10366','10118','10119','10285','10466','10579','10440','10542','10717','10668','10120','10121','10122','10284','10704'))
        OR (app.NO_APLIKASI > '20190805' AND app.BRANCH_CODE IN('10024','10042','10151','10152','10153','10241','10297','10298','10560','10421','10190','10247','10325','10612',
            '10009','10094','10096','10272','10095','10414','10097','10556','10358','10359','10360','10574','10608',
            '10357','10091','10092','10093','10050','10573','10336','10488','10644','10207','10334','10083','10084','10271'))
        OR (app.NO_APLIKASI > '20191004' AND app.BRANCH_CODE IN('10023','10036','10041','10178','10179','10295','10296','10315','10326','10410','10450','10535','10541','10576','10642','10648'))
        OR (app.NO_APLIKASI > '20191004' AND app.BRANCH_CODE IN('10026','10155','10156','10242','10299','10370','10403','10447','10491','10525','10548'))
        OR (app.NO_APLIKASI > '20191007' AND app.BRANCH_CODE IN('10049','10030','10043','10087','10191','10192','10204','10205','10206','10223','10306','10327','10328','10333','10356','10442','10481'))
        OR (app.NO_APLIKASI > '20191009' AND app.BRANCH_CODE IN('10037','10180','10181','10182','10183','10489','10411','10490','10643','10316'))
        OR (app.NO_APLIKASI > '20191010' AND app.BRANCH_CODE IN('10027','10039','10157','10186','10220','10221','10222','10225','10226','10300','10320','10385','10465','10496','10538','10615','10640'))
        OR (app.NO_APLIKASI > '20191014' AND app.BRANCH_CODE IN('10019','10139','10140','10137','10138','10063','10141','10239','10240','10290','10291','10585','10443','10335','10559','10352','10638'))
        OR (app.NO_APLIKASI > '20191016' AND app.BRANCH_CODE IN('10022','10044','10147','10148','10149','10150','10193','10194','10227','10293','10294','10423','10446','10477','10484','10504','10508','10546','10549','10550','10667'))
        OR (app.NO_APLIKASI > '20191016' AND app.BRANCH_CODE IN('10032','10056','10167','10168','10209','10310','10341','10437','10527','10645','10649'))
        OR (app.NO_APLIKASI > '20191021' AND app.BRANCH_CODE IN('10034','10059','10172','10224','10228','10312','10313','10342','10417','10475','10568','10672'))
        OR (app.NO_APLIKASI > '20191023' AND app.BRANCH_CODE IN('10011','10111','10210','10215','10216','10217','10219','10277','10278','10346','10365','10495','10561','10652'))
        OR (app.NO_APLIKASI > '20191104' AND app.BRANCH_CODE IN('10008','10088','10089','10214','10266','10270','10361','10507','10544','10545','10613'))
        OR (app.NO_APLIKASI > '20191104' AND app.BRANCH_CODE IN('10353','10025','10047','10055','10090','10154','10158','10159','10213','10218','10267','10268','10269','10486','10539','10616'))
    )
    AND (app.FLOW_CODE NOT LIKE '%_HOLD%')
`;

export async function GET() {
  try {
    const exportDate = getTodayJakarta();
    const data = await executeQuery(DASHBOARD_DAILY_EXPORT_QUERY, { p_tgl: exportDate });

    return NextResponse.json({
      success: true,
      data,
      meta: { exportDate },
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 },
    );
  }
}

export const dynamic = "force-dynamic";
